apiVersion: v1
kind: Service
metadata:
  name: aegis-mint-auth-service
spec:
  selector:
    app: aegis-mint-auth
  ports:
    - protocol: TCP
      port: 80         # The public-facing port
      targetPort: 3000 # The port your app is listening on inside the container
  type: LoadBalancer   # This provisions a public IP address on Google Cloud
